### ISSUE TITLE
nodes never join

### ISSUE THREAD

**Issue by devMls** [mtsinput/sql_ha#1]
Hi

I am trying to deploy this docker compose, but when nodes started, don't achieve find others because they are starting, and never joins always fail conect.

i suppose that is beacuse no bootstrap node is present, but i can't fix it. any help is welcome

**Comment by mtsinput** [comment]
In repo you could get docker-compose file as a sample of deploy. Pay
attention, that sample is developed for Docker SWARM.

ср, 1 дек. 2021 г. в 13:19, devMls ***@***.***>:
